### ISSUE TITLE
Use of undeclared type 'WKExtensionDelegate'

### ISSUE THREAD

**Issue by DZetko** [kristinathai/WatchOS2WatchConnectivityDemos#1]
After importing WatchKit to the ExtensionDelegate.swift, Xcode 7 still throws this error: Use of undeclared type 'WKExtensionDelegate'. Is there any solution to this problem?

Thank you, DZetko.

**Comment by krstnfx** [comment]
Haven't seen this in my version of Xcode. Are you on the latest beta?

ExtensionDelegate.swift should already have watchkit imported by default when you create the project.

**Comment by krstnfx** [comment]
Not reproducible

**Comment by matthewferguson** [comment]
Ya, I have the same issue.  All info.plist are very similar.  It's as though Xcode is not reading the info.plist in the Extension area.  DZetko, what happened with your project.  How did you eventually remove this problem.
